# Generated by Django 4.2.3 on 2023-08-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identificação')),
                ('memo', models.TextField(verbose_name='Memo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='S', max_length=1, verbose_name='Tipo')),
                ('efetivado', models.BooleanField(default=False, help_text='Diz se a transação bancária foi aplicada na conta bancária real.', verbose_name='Efetivada')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('ignorada', 'Ignorada'), ('inativa', 'Inativa')], default='ativa', help_text='Diz se a transação pode alterar o saldo da conta bancária ou ser usada em estatísticas.', max_length=8, verbose_name='Status')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoria')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transacoes.transacao')),
            ],
        ),
    ]
