# Generated by Django 4.2.4 on 2023-08-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_planejamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamento',
            options={'ordering': ['-mes'], 'verbose_name': 'Planejamento', 'verbose_name_plural': 'Planejamentos'},
        ),
        migrations.RemoveField(
            model_name='planejamento',
            name='repetir_mensalmente',
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='repeticoes',
            field=models.IntegerField(default=0, help_text='Quantidade de meses que o planejamento deve ser repetido. 0 para se repetir mensalmente.', verbose_name='Repetições'),
        ),
    ]
